Side panels can now be hidden through configuration
OpenUpSA/wazimap-ng-ui pull request #262
Opened 2021-02-24 10:24 UTC by adieyal

## Description

Side panel visibility can now be configured.

## Related Issue
https://github.com/OpenUpSA/wazimap-ng-ui/issues/261

## How to test it locally

In the profile config, you can add the following top-level key:
`
"panels": {
    "point_data": {
      "visible": false
    }
  },
`
This will hide the point data side panel. rich_data and data_explorer can also be used. Documentation can be found here: https://app.gitbook.com/@openup/s/wazi-ng-technical/profile-configuation

## Screenshots

## Changelog
Added a configuration and hide side panel mechanism

### Added

### Updated

### Removed

## Checklist

- [x]  🚀 is the code ready to be merged and go live?
- [x]  🛠 does it work (build) locally
- [ ] 👩‍🎨 does the design matches the [Demo](https://wazimap-ng-v1.webflow.io/demo)

### Pull Request

- [x]  📰 good title
- [x]  📝good description
- [x]  🔖 issue linked
- [x]  📖 changelog filled out
- [x] commit messages are meaningful

### Code Quality

- [x]  🚧 no commented out code
- [x]  🖨 no unnecessary logging
- [x]  🎱 no magic numbers

### Testing

- [ ]  ✅ added (appropriate) unit tests
- [ ]  💢 edge cases in tests were considered
- [ ]  ✅ ran tests locally & are passing

2021-02-25 09:53 UTC, milafrerichs requested changes
works, that it is hiding the panel. but the point mapper panel is active by default 
and therefore visible without a tab. 
we should probably add a default panel to the config as well, right?

2021-02-26 07:59 UTC, adieyal commented
It is implement, but needs to be better documented: https://openup.gitbook.io/wazi-ng-technical/profile-configuation

2021-03-02 09:15 UTC, milafrerichs approved these changes

2021-03-02 09:15 UTC, milafrerichs commented
could be refactored at some point.

2021-03-02 09:36 UTC, merged