negative range
OpenUpSA/wazimap-ng-ui pull request #665
Opened 2022-11-13 19:27 UTC by emre2038

## Description

A meaningful description of proposed change in your own words.

## Related Issue

## How is it tested automatically?

> Is the particular functionality/structure of the backend API this relies on tested?
> What unit, integration, GUI, end-to-end tests were added to test the functionality implemented/fixed in this PR?
> What other tests does it rely on so that the new tests are sufficient?

## How should a reviewer test it locally

## Screenshots

## Changelog

### Added

### Updated

### Removed

## Checklist

- [ ]  🚀 is the code ready to be merged and go live?
- [ ]  🛠 does it work (build) locally
- [ ] 👩‍🎨 does the design match the [Demo](https://wazimap-ng-v1.webflow.io/demo)

### Pull Request

- [ ]  📰 good title
- [ ]  📝good description
- [ ]  🔖 issue linked
- [ ]  📖 changelog filled out
- [ ] commit messages are meaningful

### Code Quality

- [ ]  🚧 no commented out code
- [ ]  🖨 no unnecessary logging
- [ ]  🎱 no magic numbers

### Testing

- [ ]  ✅ added (appropriate) unit tests
- [ ]  💢 edge cases in tests were considered
- [ ]  ✅ ran tests locally & are passing

2022-11-18 06:18 UTC, goyal1092 requested changes
Chart will not show up if all values are negative.
https://github.com/OpenUpSA/wazimap-ng-ui/blob/staging/src/js/profile/blocks/indicator.js#L16 will return false.

2022-11-21 13:09 UTC, michaelglenister reviewed
So far so good, units tests cover the changes. Just one small comment about variable type

If you can address that then this is ready to go

2022-11-21 13:09 UTC, michaelglenister commented on src/js/elements/mapchip/legend.js
> +            if (!isColorLight(colors[i])) {
I like that the comment explaining isColorLight is in the utils file, so it doesn't clutter this code but is easy to find if someone looks deeper

2022-11-22 07:10 UTC, emre2038 commented on src/js/map/maps.js
> +        const positiveColorScale = this.choropleth.getScale([bounds.lower, bounds.upper], [positiveColorRange[0], positiveColorRange[1]]);
great idea - it made sense a lot to me. I updated the code

2022-11-30 07:25 UTC, michaelglenister approved these changes

2022-11-30 07:26 UTC, michaelglenister commented
Approved the changes but just remember to have CI passing, or a card to fix it in the backlog

2022-12-06 11:51 UTC, jbothma commented on src/js/configurations/geography_sa.js
> +            negative_color_range: ["#fef0d9", "#b30000"],
you fell into the same trap as me

here the right-hand item is the more intense colour, but you're using item 0 in the array as the most intense one when there are both positive and negative values.

2022-12-06 11:56 UTC, jbothma commented on src/js/configurations/geography_sa.js
> +            negative_color_range: ["#fef0d9", "#b30000"],
so I think the way it's used at https://github.com/OpenUpSA/wazimap-ng-ui/pull/665/files#diff-b2dbf83a3b8c7fe11dcab6b7b935a18c36ffbf277c9e6dbff75a0324de0c03dcR140 is fine - we could document that as "negative max", but then make the defaults be the right order: item 0 negative max, item 1 negative minimum

2022-12-07 06:09 UTC, merged